version: "3.3"
services:
  mc:
    image: "itzg/minecraft-server"
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - MEMORY=${MEMORY}
      - VERSION=${VERSION}
    volumes:
      - ./minecraft-data:/data
    restart: "unless-stopped"